### PR TITLE
ADD SocialMeta File and Some other changes on repo

### PR DESCRIPTION
**Pull request by ianujvarshney**
- i did npm install react-helmet-async Package.
- i did Create a 'SocialMeta' File in Components Folder.
- i did set Route of SocialMeta File in App.js File.

### CODE REVIEW

**Review by adityasimant — COMMENTED** [review]
LGTM, @riteshsonawane1372 is there a need to push package-lock.json?

**Comment by ianujvarshney** [comment]
> LGTM, @riteshsonawane1372 is there a need to push package-lock.json?

Hello @adityasimant. Sorry for but if my opinion.  Actually, there's no need for manual installation since it will be installed automatically. It's already in your repository, which is why I pushed it there.

**Comment by adityasimant** [comment]
It doesn't matter as we have to install the dependencies anyways..

**Comment by ianujvarshney** [comment]
> It doesn't matter as we have to install the dependencies anyways.. 

Yes @adityasimant

**Comment by ianujvarshney** [comment]
> It doesn't matter as we have to install the dependencies anyways.. 

So what should I do ?

**Comment by adityasimant** [comment]
@riteshsonawane1372 is managing this issue. He'll merge your PR after reviewing it.

**Pull request merged**
