### PR TITLE
Event#120

### LINKED ISSUE #120: Add events section in homepage
Add a section on the homepage "Check out our recent events!" which should have a title, description and a button that redirects to "/events".

### PR DESCRIPTION
**Pull request by ianujvarshney**
# Pull Request

## Changes Made:
- Fixed the issue reported.
- Added a new 'Recent' section in the home section.
- Included necessary CSS for styling.

## Additional Details:
- Any relevant information or context that would help reviewers understand the changes made.

Fixes #120

### CODE REVIEW

**Review by adityasimant — APPROVED** [review]
LGTM

**Comment by adityasimant** [comment]
Can you provide some screenshots so I can merge it

**Comment by ianujvarshney** [comment]
- Check it  [Video](https://watch.screencastify.com/v/OHPsi2YtcAiIcXjgEKVT)

**Comment by adityasimant** [comment]
That looks good! However, I noticed that your code is from the previous page version. Many things have been updated. Could you pull the new code and run the app? Also, the underconst svg you used in "/Home" is not needed instead do this: 
1. Go to [Undraw](https://undraw.co/) Browse and search for Team Collaboration 
2. Download the SVG in red colour format.
3. Paste the SVG in the assets folder.
4. And use that on the homepage.
5. Make the PR when you're done.

Note that the event section is not empty and has some events that have been carried out recently so you don't need to use the SVG in "/Events"

**Pull request closed without merging**
