### PR TITLE
done with #adding better logos

### PR DESCRIPTION
**Pull request by Akshayp02**
I've made changes with better logos by rearing [WeMakeDevs's](https://github.com/WeMakeDevs/wemakedevs) ❤️

### CODE REVIEW

**Review by adityasimant — CHANGES_REQUESTED** [review]
1. Remove the Threads logo we don't need a Threads account.
2. Use a better logo for Instagram as it has a problem rendering. Make sure to test it before making a PR.

**Comment by adityasimant** [comment]
I have removed the logos. You just have to add a good Instagram logo with link that renders.

**Comment by adityasimant** [comment]
Also, mention the issue you're working on in the PR message. Thanks

**Review by adityasimant — APPROVED** [review]

**Comment by adityasimant** [comment]
#27 completed

**Review by Akshayp02 — COMMENTED** [review]
okay

**Pull request merged**
