### PR TITLE
Add social meta tags with react-helmet-async and update boilerplate text

### PR DESCRIPTION
**Pull request by pratiktarway29**
feat: Implement react-helmet-async for SEO meta tags

- Added react-helmet-async to manage meta tags dynamically.
- Updated meta tags for better SEO and social sharing.
- Created a SocialMeta component to handle meta tags.
- Applied the SocialMeta component to the /socialmeta-page route.

### CODE REVIEW

**Comment by riteshsonawane1372** [comment]
@pratiktarway29 update ur `main` branch

**Comment by pratiktarway29** [comment]
@riteshsonawane1372  I've updated my main branch

**Comment by adityasimant** [comment]
You're pushing the package-lock.json file. If you can remove that from the commit I'll merger this PR.

**Comment by adityasimant** [comment]
Also create an issue about your PR and mention it in your PR.

**Comment by pratiktarway29** [comment]
@adityasimant I've removed package-lck.json, kindly merge this PR.

**Comment by riteshsonawane1372** [comment]
@pratiktarway29 I have mentioned some changes pls do that. And pls change your main branch to this commit `[13671f1]`. There was some miscommunication, we need the package-lock.json file for now

**Comment by pratiktarway29** [comment]
@riteshsonawane1372 What changes do you want me to make, List them point-wise.

**Comment by riteshsonawane1372** [comment]
> @riteshsonawane1372 What changes do you want me to make, List them point-wise.
@pratiktarway29 do check this

https://github.com/DIEMS-HUB/IETE-Website/pull/93/files

**Pull request closed without merging**
